default-task = 'build'
version = 0.1

extensions = ['chomp@0.1:jspm', 'chomp@0.1:npm']

[template-options.npm]
auto-install = true

[[task]]
deps = ['build:packages', 'build:apps']
name = "buile:all"
target = 'dist/*.js'
template = 'jspm'
[task.template-options]
env = ['browser', 'development', 'module']

[[task]]
name = "build:packages"
deps = ['src/**/*.ts']
target = 'dist/#.js'
template = 'jspm'
[task.template-options]
env = ['browser', 'development', 'module']
