default-task = 'build'
version = 0.1

extensions = ['chomp@0.1:bun', 'chomp@0.1:jspm', 'chomp@0.1:npm']

[template-options.npm]
auto-install = true

[[task]]
name = 'build'
deps = ['ts']

[[task]]
name = 'ts'
dep = 'src/#.ts'
target = 'dist/#.js'
template = 'bun'
