# https://taskfile.dev

version: '3'

includes:
  core:
    taskfile: ./taskfile.yml
    dir: ./packages/core
  web:
    taskfile: ./taskfile.yml
    dir: ./packages/web
  components:
    taskfile: ./taskfile.yml
    dir: ./packages/components
  demo:
    taskfile: ./taskfile.yml
    dir: ./apps/demo

tasks:
  default:
    desc: Display all available tasks
    cmds:
      - task: list

  list:
    desc: List all tasks
    cmds:
      - task -l

  build:
    desc: Build the project
    cmds:
      - task: clean
      - task: build:ts
      - task: build:typings

  clean:
    desc: Clean the project
    cmds:
      - rm -rf dist

  build:ts:
    desc: Build typescript
    cmds:
      - bun build src/**/*.ts --root src --outdir dist --target browser --experimental-css --splitting --packages external --packages external --sourcemap=linked

  build:typings:
    desc: Build typings
    cmds:
         - bun tsc -p tsconfig.types.json
