default-task = 'build'
version = 0.1

extensions = ['chomp@0.1:jspm', 'chomp@0.1:npm']

[template-options.npm]
auto-install = true

[[task]]
name = 'clean'
run = '''
  rm -rf dist
  mkdir dist
  '''
validation = 'none'

[[task]]
name = "build"
deps = ['clean', 'src/##.ts']
target = 'dist'
run = 'bun build src/index.ts --packages external --sourcemap=linked --outdir dist --splitting --packages external --target bun --root ./src'
[task.template-options]
env = ['browser', 'development', 'module']
