# https://taskfile.dev

version: '3'

tasks:
  default:
    desc: Display all available tasks
    cmds:
      - task: list

  list:
    desc: List all tasks
    cmds:
      - task -l

  build:
    desc: Build the project
    cmds:
      - task: clean
      - task: build:ts

  clean:
    desc: Clean the project
    cmds:
      - rm -rf dist

  build:ts:
    desc: Build typescript
    cmds:
      - bun build src/**/*.ts --root src --outdir dist --target browser --experimental-css --splitting --packages external --packages external --sourcemap=linked
