# https://taskfile.dev

version: '3'

tasks:
  build:
    desc: Build the project
    cmds:
      - task: build:clean
      - task: build:ts

  build:clean:
    internal: true
    desc: Clean the project
    cmds:
      - rm -rf dist

  build:ts:
    desc: Build typescript
    deps: [build:clean]
    cmds:
      - bun build src/**/*.ts --root src --outdir dist --target browser --experimental-css --splitting --packages external --packages external --sourcemap=linked
